extends Node2D

# Color Sort — a Ball Sort Puzzle style game. Tap a tube to pick up its top
# color, tap another to pour it in (legal only onto an empty tube or one
# whose top color matches). Get every tube down to a single color to solve
# the puzzle. No timer and no reflexes at all — a pure planning puzzle,
# the only game in the studio with that pacing. A shared move budget
# (rather than a per-puzzle fail state) creates the risk/reward: solving
# refills some moves, so efficient play keeps the run alive longer.
#
# Note: puzzles are generated by randomly distributing colors into tubes
# (with empty tubes for maneuvering room), the standard approach for this
# genre. Solvability isn't formally proven for every deal — same as most
# mobile ball-sort games, an unlucky deal is rare but possible.

# Structural addition: variable tube capacity. Instead of every tube
# sharing one fixed size, each tube in a puzzle rolls its own capacity
# (3-5). Every color still only ever has MIN_CAPACITY balls, so any tube
# can still hold a full color if maneuvered there — solvable by
# construction — but the uneven capacities change the maneuvering-room
# math: a capacity-5 tube is generous parking space, a capacity-3 tube
# fills up fast and forces earlier commitments.
const MIN_CAPACITY := 3
const MAX_CAPACITY := 5
const BALL_COUNT_PER_COLOR := MIN_CAPACITY
const BASE_COLOR_COUNT := 4
const MAX_COLOR_COUNT := 5
const EMPTY_TUBES := 2
const SOLVES_PER_DIFFICULTY_STEP := 3
const STARTING_MOVES := 40
const MOVE_BONUS_PER_SOLVE := 10
const SAVE_PATH := "user://colorsort_highscore.cfg"

const TUBE_WIDTH := 64.0
const TUBE_HEIGHT := 260.0
const TUBE_SPACING := 14.0
const TUBES_TOP := 320.0
const BALL_RADIUS := 26.0
const BALL_GAP := 4.0

const TUBE_COLOR := Color(0.28, 0.3, 0.34, 1.0)
const TUBE_SELECTED_COLOR := Color(0.35, 0.55, 0.78, 1.0)

# Novelty twist: a rare wildcard ball pours onto (and accepts pours from)
# any color — mirrors Merge Numbers' wildcard tile, applied to a stacking
# puzzle instead of a slide-merge one. A studio-wide "wildcards show up
# across genres" motif.
const WILDCARD := -1
const WILDCARD_CHANCE_PER_PUZZLE := 0.35
const WILDCARD_COLOR := Color(0.92, 0.92, 0.95, 1.0)

# Novel element: Locked Tube. A rare tube starts sealed — no pouring into
# or out of it — for the puzzle's first few moves (counted across the
# whole puzzle, not just moves touching that tube), then unlocks for the
# rest of the puzzle. Adds tempo pressure: plan around one tube being
# temporarily off-limits.
const LOCKED_TUBE_CHANCE_PER_PUZZLE := 0.3
const LOCK_DURATION_MOVES := 4
const LOCKED_TUBE_COLOR := Color(0.55, 0.45, 0.15, 1.0)
var locked_tube_index: int = -1
var locked_moves_remaining: int = 0

@onready var tubes_container: Node2D = $TubesContainer
@onready var score_label: Label = $ScoreLabel
@onready var moves_label: Label = $MovesLabel
@onready var ready_overlay: ColorRect = $ReadyOverlay
@onready var game_over_overlay: ColorRect = $GameOverOverlay
@onready var game_over_score_label: Label = $GameOverOverlay/GameOverScore

var tubes: Array = []
var tube_capacities: Array = []
var selected_tube: int = -1
var color_count: int = BASE_COLOR_COUNT

var solved_count: int = 0
var high_score: int = 0
var moves: int = STARTING_MOVES
var game_over: bool = false
var game_started: bool = false


func _ready() -> void:
	_load_high_score()
	_start_game()


func _start_game() -> void:
	solved_count = 0
	color_count = BASE_COLOR_COUNT
	moves = STARTING_MOVES
	game_over = false
	game_started = false
	selected_tube = -1
	score_label.text = "Solved: 0"
	moves_label.text = "Moves: %d" % moves
	game_over_overlay.visible = false
	ready_overlay.visible = true
	_generate_puzzle()


func _generate_puzzle() -> void:
	var pool: Array = []
	for c in range(color_count):
		for _i in range(BALL_COUNT_PER_COLOR):
			pool.append(c)
	pool.shuffle()
	if randf() < WILDCARD_CHANCE_PER_PUZZLE:
		pool[randi() % pool.size()] = WILDCARD

	tubes.clear()
	tube_capacities.clear()
	var idx := 0
	for _c in range(color_count):
		var t: Array = []
		for _i in range(BALL_COUNT_PER_COLOR):
			t.append(pool[idx])
			idx += 1
		tubes.append(t)
		tube_capacities.append(randi_range(MIN_CAPACITY, MAX_CAPACITY))
	for _e in range(EMPTY_TUBES):
		tubes.append([])
		tube_capacities.append(randi_range(MIN_CAPACITY, MAX_CAPACITY))

	if randf() < LOCKED_TUBE_CHANCE_PER_PUZZLE:
		locked_tube_index = randi() % tubes.size()
		locked_moves_remaining = LOCK_DURATION_MOVES
	else:
		locked_tube_index = -1
		locked_moves_remaining = 0

	selected_tube = -1
	_redraw_tubes()


func _top_run_count(tube: Array) -> int:
	if tube.is_empty():
		return 0
	var color: int = tube.back()
	var count := 0
	for i in range(tube.size() - 1, -1, -1):
		if tube[i] == color:
			count += 1
		else:
			break
	return count


func _is_locked(idx: int) -> bool:
	return locked_moves_remaining > 0 and idx == locked_tube_index


func _can_pour(src: int, dst: int) -> bool:
	if _is_locked(src) or _is_locked(dst):
		return false
	if tubes[src].is_empty():
		return false
	if tubes[dst].size() >= tube_capacities[dst]:
		return false
	if tubes[dst].is_empty():
		return true
	var src_top: int = tubes[src].back()
	var dst_top: int = tubes[dst].back()
	return src_top == dst_top or src_top == WILDCARD or dst_top == WILDCARD


func _pour(src: int, dst: int) -> void:
	var color: int = tubes[src].back()
	var run: int = _top_run_count(tubes[src])
	var space: int = tube_capacities[dst] - tubes[dst].size()
	var move_count: int = min(run, space)
	for _i in range(move_count):
		tubes[src].pop_back()
		tubes[dst].append(color)


func _is_solved() -> bool:
	# A tube counts as settled once it's monochrome — it no longer has to
	# be full, since capacity is decoupled from each color's ball count.
	for t in tubes:
		if t.is_empty():
			continue
		var color: int = WILDCARD
		for v in t:
			if v != WILDCARD:
				if color == WILDCARD:
					color = v
				elif v != color:
					return false
	return true


func _circle_points(radius: float, segments: int) -> PackedVector2Array:
	var pts := PackedVector2Array()
	for i in range(segments):
		var a: float = i * TAU / segments
		pts.append(Vector2(cos(a), sin(a)) * radius)
	return pts


func _color_for(c: int) -> Color:
	if c == WILDCARD:
		return WILDCARD_COLOR
	var hue: float = float(c) / float(MAX_COLOR_COUNT)
	return Color.from_hsv(hue, 0.75, 0.85, 1.0)


func _redraw_tubes() -> void:
	for c in tubes_container.get_children():
		c.queue_free()

	var tube_count: int = tubes.size()
	var total_w: float = tube_count * TUBE_WIDTH + (tube_count - 1) * TUBE_SPACING
	var origin_x: float = (540.0 - total_w) / 2.0

	for i in range(tube_count):
		var tube_x: float = origin_x + i * (TUBE_WIDTH + TUBE_SPACING)
		var capacity: int = tube_capacities[i]
		var tube_height: float = TUBE_HEIGHT * float(capacity) / float(MAX_CAPACITY)
		var tube_top: float = TUBES_TOP + (TUBE_HEIGHT - tube_height)

		var bg := ColorRect.new()
		bg.size = Vector2(TUBE_WIDTH, tube_height)
		bg.position = Vector2(tube_x, tube_top)
		if i == selected_tube:
			bg.color = TUBE_SELECTED_COLOR
		elif _is_locked(i):
			bg.color = LOCKED_TUBE_COLOR
		else:
			bg.color = TUBE_COLOR
		tubes_container.add_child(bg)

		var t: Array = tubes[i]
		for slot in range(t.size()):
			var ball := Polygon2D.new()
			ball.polygon = _circle_points(BALL_RADIUS, 16)
			var ball_y: float = tube_top + tube_height - 8.0 - slot * (BALL_RADIUS * 2.0 + BALL_GAP) - BALL_RADIUS
			ball.position = Vector2(tube_x + TUBE_WIDTH / 2.0, ball_y)
			ball.color = _color_for(t[slot])
			tubes_container.add_child(ball)


func _tube_index_at(pos: Vector2) -> int:
	var tube_count: int = tubes.size()
	if tube_count == 0 or pos.y < TUBES_TOP or pos.y > TUBES_TOP + TUBE_HEIGHT:
		return -1
	var total_w: float = tube_count * TUBE_WIDTH + (tube_count - 1) * TUBE_SPACING
	var origin_x: float = (540.0 - total_w) / 2.0
	for i in range(tube_count):
		var tube_x: float = origin_x + i * (TUBE_WIDTH + TUBE_SPACING)
		if pos.x >= tube_x and pos.x <= tube_x + TUBE_WIDTH:
			return i
	return -1


func _input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo:
		if not game_started:
			game_started = true
			ready_overlay.visible = false
			return
		if game_over:
			_start_game()
			return
		if event.keycode >= KEY_1 and event.keycode <= KEY_9:
			var idx: int = event.keycode - KEY_1
			if idx < tubes.size():
				_on_tube_tapped(idx)
		return

	var pos: Vector2
	var pressed := false
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		pos = event.position
		pressed = true
	elif event is InputEventScreenTouch and event.pressed:
		pos = event.position
		pressed = true

	if not pressed:
		return

	if not game_started:
		game_started = true
		ready_overlay.visible = false
		return
	if game_over:
		_start_game()
		return

	var idx: int = _tube_index_at(pos)
	if idx != -1:
		_on_tube_tapped(idx)


func _on_tube_tapped(idx: int) -> void:
	if _is_locked(idx):
		return

	if selected_tube == -1:
		if not tubes[idx].is_empty():
			selected_tube = idx
			_redraw_tubes()
		return

	if idx == selected_tube:
		selected_tube = -1
		_redraw_tubes()
		return

	if _can_pour(selected_tube, idx):
		_pour(selected_tube, idx)
		selected_tube = -1
		moves -= 1
		moves_label.text = "Moves: %d" % moves
		if locked_moves_remaining > 0:
			locked_moves_remaining -= 1
			if locked_moves_remaining <= 0:
				locked_tube_index = -1
		if _is_solved():
			_on_puzzle_solved()
		elif moves <= 0:
			_trigger_game_over()
		_redraw_tubes()
	else:
		selected_tube = idx if not tubes[idx].is_empty() else -1
		_redraw_tubes()


func _on_puzzle_solved() -> void:
	solved_count += 1
	score_label.text = "Solved: %d" % solved_count
	moves += MOVE_BONUS_PER_SOLVE
	moves_label.text = "Moves: %d" % moves
	if solved_count % SOLVES_PER_DIFFICULTY_STEP == 0:
		color_count = min(MAX_COLOR_COUNT, color_count + 1)
	_generate_puzzle()


func _trigger_game_over() -> void:
	game_over = true
	if solved_count > high_score:
		high_score = solved_count
		_save_high_score()
	game_over_score_label.text = "Solved: %d  Best: %d" % [solved_count, high_score]
	game_over_overlay.visible = true


func _load_high_score() -> void:
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) == OK:
		high_score = int(cfg.get_value("scores", "high_score", 0))


func _save_high_score() -> void:
	var cfg := ConfigFile.new()
	cfg.set_value("scores", "high_score", high_score)
	cfg.save(SAVE_PATH)
